const baseBackendUrl = 'https://localhost:7006'
const apiUrl = `${baseBackendUrl}/api/v1`
export const userManagementApiUrl = `${apiUrl}/UserManagement`;
export const userImagesApiUrl = `${apiUrl}/UserImages`;
export const basketApiUrl = `${apiUrl}/basket`;
export const gamesApiUrl = `${apiUrl}/game`;
export const gameImagesApiUrl = `${apiUrl}/gameImages`;
export const gameGenresApiUrl = `${apiUrl}/gameGenre`;
export const companiesApiUrl = `${apiUrl}/company`;